// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PsicoFinance.Infrastructure.Persistence;

#nullable disable

namespace PsicoFinance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PsicoFinance.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("acao");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinica_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_anteriores");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_novos");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidade_id");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("excluido_em");

                    b.Property<string>("IpOrigem")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_origem");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ClinicaId")
                        .HasDatabaseName("ix_audit_logs_clinica_id");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_audit_logs_criado_em");

                    b.HasIndex("Entidade", "EntidadeId")
                        .HasDatabaseName("ix_audit_logs_entidade_entidade_id");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Clinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("estado")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("excluido_em");

                    b.Property<TimeOnly>("HorarioEnvioAlerta")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_envio_alerta");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("America/Sao_Paulo")
                        .HasColumnName("timezone");

                    b.Property<string>("WebhookN8nUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("webhook_n8n_url");

                    b.HasKey("Id")
                        .HasName("pk_clinicas");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_clinicas_cnpj")
                        .HasFilter("cnpj IS NOT NULL");

                    b.ToTable("clinicas");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinica_id");

                    b.Property<bool>("CobraFaltaInjustificada")
                        .HasColumnType("boolean")
                        .HasColumnName("cobra_falta_injustificada");

                    b.Property<bool>("CobraFaltaJustificada")
                        .HasColumnType("boolean")
                        .HasColumnName("cobra_falta_justificada");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<string>("DiaSemanasessao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dia_semanasessao");

                    b.Property<int>("DuracaoMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("duracao_minutos");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("excluido_em");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("frequencia");

                    b.Property<TimeOnly>("HorarioSessao")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_sessao");

                    b.Property<string>("MotivoEncerramento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_encerramento");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid?>("PlanoContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_conta_id");

                    b.Property<Guid>("PsicologoId")
                        .HasColumnType("uuid")
                        .HasColumnName("psicologo_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorSessao")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_sessao");

                    b.HasKey("Id")
                        .HasName("pk_contratos");

                    b.HasIndex("ClinicaId")
                        .HasDatabaseName("ix_contratos_clinica_id");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_contratos_paciente_id");

                    b.HasIndex("PlanoContaId")
                        .HasDatabaseName("ix_contratos_plano_conta_id");

                    b.HasIndex("PsicologoId")
                        .HasDatabaseName("ix_contratos_psicologo_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_contratos_status");

                    b.ToTable("contratos");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.LancamentoFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinica_id");

                    b.Property<string>("Competencia")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("competencia");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("excluido_em");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("PlanoContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_conta_id");

                    b.Property<Guid?>("SessaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_lancamentos_financeiros");

                    b.HasIndex("PlanoContaId")
                        .HasDatabaseName("ix_lancamentos_financeiros_plano_conta_id");

                    b.HasIndex("SessaoId")
                        .HasDatabaseName("ix_lancamentos_financeiros_sessao_id");

                    b.HasIndex("ClinicaId", "DataVencimento")
                        .HasDatabaseName("ix_lancamentos_financeiros_clinica_id_data_vencimento");

                    b.HasIndex("ClinicaId", "Competencia", "Status")
                        .HasDatabaseName("ix_lancamentos_financeiros_clinica_id_competencia_status");

                    b.ToTable("lancamentos_financeiros");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinica_id");

                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("excluido_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("ResponsavelNome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("responsavel_nome");

                    b.Property<string>("ResponsavelTelefone")
                        .HasColumnType("text")
                        .HasColumnName("responsavel_telefone");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_pacientes");

                    b.HasIndex("ClinicaId")
                        .HasDatabaseName("ix_pacientes_clinica_id");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.PlanoConta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinica_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("excluido_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_planos_conta");

                    b.HasIndex("ClinicaId", "Nome", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ix_planos_conta_clinica_id_nome_tipo");

                    b.ToTable("planos_conta");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Psicologo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agencia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("agencia");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Banco")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("banco");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinica_id");

                    b.Property<string>("Conta")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("conta");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Crp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("crp");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("excluido_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("PixChave")
                        .HasColumnType("text")
                        .HasColumnName("pix_chave");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<string>("TipoRepasse")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_repasse");

                    b.Property<decimal>("ValorRepasse")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_repasse");

                    b.HasKey("Id")
                        .HasName("pk_psicologos");

                    b.HasIndex("ClinicaId", "Crp")
                        .IsUnique()
                        .HasDatabaseName("ix_psicologos_clinica_id_crp");

                    b.ToTable("psicologos");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinica_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("excluido_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expira_em");

                    b.Property<string>("IpOrigem")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_origem");

                    b.Property<bool>("Revogado")
                        .HasColumnType("boolean")
                        .HasColumnName("revogado");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revogado_em");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ClinicaId")
                        .HasDatabaseName("ix_refresh_tokens_clinica_id");

                    b.HasIndex("ExpiraEm")
                        .HasDatabaseName("ix_refresh_tokens_expira_em");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Repasse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinica_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("excluido_em");

                    b.Property<string>("MesReferencia")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("mes_referencia");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("PsicologoId")
                        .HasColumnType("uuid")
                        .HasColumnName("psicologo_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<int>("TotalSessoes")
                        .HasColumnType("integer")
                        .HasColumnName("total_sessoes");

                    b.Property<decimal>("ValorCalculado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_calculado");

                    b.HasKey("Id")
                        .HasName("pk_repasses");

                    b.HasIndex("PsicologoId")
                        .HasDatabaseName("ix_repasses_psicologo_id");

                    b.HasIndex("ClinicaId", "PsicologoId", "MesReferencia")
                        .IsUnique()
                        .HasDatabaseName("ix_repasses_clinica_id_psicologo_id_mes_referencia");

                    b.ToTable("repasses");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Sessao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinica_id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<int>("DuracaoMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("duracao_minutos");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("excluido_em");

                    b.Property<TimeOnly>("HorarioInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_inicio");

                    b.Property<string>("MotivoFalta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_falta");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("PsicologoId")
                        .HasColumnType("uuid")
                        .HasColumnName("psicologo_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sessoes");

                    b.HasIndex("ClinicaId")
                        .HasDatabaseName("ix_sessoes_clinica_id");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_sessoes_data");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_sessoes_paciente_id");

                    b.HasIndex("PsicologoId")
                        .HasDatabaseName("ix_sessoes_psicologo_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sessoes_status");

                    b.HasIndex("ContratoId", "Data")
                        .HasDatabaseName("ix_sessoes_contrato_id_data");

                    b.ToTable("sessoes");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinica_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("excluido_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("PsicologoId")
                        .HasColumnType("uuid")
                        .HasColumnName("psicologo_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<DateTimeOffset?>("UltimoAcessoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ultimo_acesso_em");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("PsicologoId")
                        .HasDatabaseName("ix_usuarios_psicologo_id");

                    b.HasIndex("ClinicaId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_clinica_id_email");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("PsicoFinance.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Contratos")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contratos_clinicas_clinica_id");

                    b.HasOne("PsicoFinance.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Contratos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contratos__pacientes_paciente_id");

                    b.HasOne("PsicoFinance.Domain.Entities.PlanoConta", "PlanoConta")
                        .WithMany("Contratos")
                        .HasForeignKey("PlanoContaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_contratos__planos_conta_plano_conta_id");

                    b.HasOne("PsicoFinance.Domain.Entities.Psicologo", "Psicologo")
                        .WithMany("Contratos")
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contratos__psicologos_psicologo_id");

                    b.Navigation("Clinica");

                    b.Navigation("Paciente");

                    b.Navigation("PlanoConta");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.LancamentoFinanceiro", b =>
                {
                    b.HasOne("PsicoFinance.Domain.Entities.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lancamentos_financeiros_clinicas_clinica_id");

                    b.HasOne("PsicoFinance.Domain.Entities.PlanoConta", "PlanoConta")
                        .WithMany()
                        .HasForeignKey("PlanoContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lancamentos_financeiros__planos_conta_plano_conta_id");

                    b.HasOne("PsicoFinance.Domain.Entities.Sessao", "Sessao")
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lancamentos_financeiros__sessoes_sessao_id");

                    b.Navigation("Clinica");

                    b.Navigation("PlanoConta");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("PsicoFinance.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Pacientes")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pacientes_clinicas_clinica_id");

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.PlanoConta", b =>
                {
                    b.HasOne("PsicoFinance.Domain.Entities.Clinica", "Clinica")
                        .WithMany("PlanosConta")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planos_conta_clinicas_clinica_id");

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Psicologo", b =>
                {
                    b.HasOne("PsicoFinance.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Psicologos")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_psicologos_clinicas_clinica_id");

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PsicoFinance.Domain.Entities.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_clinicas_clinica_id");

                    b.HasOne("PsicoFinance.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens__usuarios_usuario_id");

                    b.Navigation("Clinica");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Repasse", b =>
                {
                    b.HasOne("PsicoFinance.Domain.Entities.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_repasses_clinicas_clinica_id");

                    b.HasOne("PsicoFinance.Domain.Entities.Psicologo", "Psicologo")
                        .WithMany()
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_repasses_psicologos_psicologo_id");

                    b.Navigation("Clinica");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Sessao", b =>
                {
                    b.HasOne("PsicoFinance.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Sessoes")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_clinicas_clinica_id");

                    b.HasOne("PsicoFinance.Domain.Entities.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_contratos_contrato_id");

                    b.HasOne("PsicoFinance.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_pacientes_paciente_id");

                    b.HasOne("PsicoFinance.Domain.Entities.Psicologo", "Psicologo")
                        .WithMany()
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_psicologos_psicologo_id");

                    b.Navigation("Clinica");

                    b.Navigation("Contrato");

                    b.Navigation("Paciente");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("PsicoFinance.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Usuarios")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_clinicas_clinica_id");

                    b.HasOne("PsicoFinance.Domain.Entities.Psicologo", "Psicologo")
                        .WithMany("Usuarios")
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usuarios_psicologos_psicologo_id");

                    b.Navigation("Clinica");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Clinica", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Pacientes");

                    b.Navigation("PlanosConta");

                    b.Navigation("Psicologos");

                    b.Navigation("Sessoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.PlanoConta", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Psicologo", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PsicoFinance.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
